/*
 * Production build for the no-bundler frontend.
 *
 * Precompiles every JSX screen listed in index.html into plain JS in
 * ui_kits/ocenka-app-v2/build/ and generates index.prod.html which loads the
 * compiled files with the production React build and WITHOUT in-browser Babel.
 *
 * The compiler is the already-vendored @babel/standalone, so no extra
 * dependencies or network access are required.
 */
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');

const rootDir = path.resolve(__dirname, '..', '..');
const appDir = path.join(rootDir, 'ui_kits', 'ocenka-app-v2');
const indexPath = path.join(appDir, 'index.html');
const prodIndexPath = path.join(appDir, 'index.prod.html');
const buildDir = path.join(appDir, 'build');

const Babel = require(path.join(appDir, 'vendor', 'babel.min.js'));

const html = fs.readFileSync(indexPath, 'utf8');
// Derive the module list (and order) straight from the dev entry so the two never drift.
const jsxFiles = [...html.matchAll(/<script type="text\/babel" src="([^"]+\.jsx)"><\/script>/g)].map((m) => m[1]);
if (!jsxFiles.length) {
  console.error('No JSX modules found in index.html — nothing to build.');
  process.exit(1);
}

fs.mkdirSync(buildDir, { recursive: true });
for (const file of fs.readdirSync(buildDir)) {
  if (file.endsWith('.js')) fs.unlinkSync(path.join(buildDir, file));
}

let compiled = 0;
for (const rel of jsxFiles) {
  const source = fs.readFileSync(path.join(appDir, rel), 'utf8');
  const { code } = Babel.transform(source, {
    presets: ['react'],
    filename: rel,
    compact: false,
  });
  const outName = rel.replace(/\.jsx$/, '.js');
  const banner = `/* Compiled from ${rel} by npm run build — do not edit. */\n`;
  fs.writeFileSync(path.join(buildDir, outName), banner + code);
  compiled += 1;
}

// Generate the production index: production React, no Babel, compiled scripts.
// Bust browser caches after each deploy (build/*.js was max-age=3600 and looked "stuck").
const buildStamp = crypto
  .createHash('sha1')
  .update(jsxFiles.map((rel) => fs.readFileSync(path.join(buildDir, rel.replace(/\.jsx$/, '.js')))).join('\0'))
  .digest('hex')
  .slice(0, 10);

let prod = html
  .replace('vendor/react.development.js', 'vendor/react.production.min.js')
  .replace('vendor/react-dom.development.js', 'vendor/react-dom.production.min.js')
  .replace(/\n\s*<script src="vendor\/babel\.min\.js"><\/script>/, '')
  .replace(/<script type="text\/babel" src="([^"]+)\.jsx"><\/script>/g, `<script src="build/$1.js?v=${buildStamp}"></script>`);
prod = `<!-- GENERATED by \`npm run build\` — do not edit. Source: index.html · v=${buildStamp} -->\n` + prod;
fs.writeFileSync(prodIndexPath, prod);

console.log(`Built ${compiled} module(s) into ui_kits/ocenka-app-v2/build/`);
console.log(`Generated ui_kits/ocenka-app-v2/index.prod.html (v=${buildStamp}, production React, no in-browser Babel).`);
