/*
 * One-command deploy via Docker Compose.
 *   npm run deploy
 *
 * Creates .env (with a generated password) if missing, then:
 *   docker compose up -d --build
 * and waits until /healthz reports ok (via Caddy on port 80).
 */
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const http = require('node:http');
const { spawnSync } = require('node:child_process');

const rootDir = path.resolve(__dirname, '..', '..');
const envPath = path.join(rootDir, '.env');
const envExample = path.join(rootDir, '.env.example');

function readEnvFile(filePath) {
  if (!fs.existsSync(filePath)) return {};
  const out = {};
  for (const line of fs.readFileSync(filePath, 'utf8').split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq < 0) continue;
    out[trimmed.slice(0, eq).trim()] = trimmed.slice(eq + 1).trim();
  }
  return out;
}

function ensureEnv() {
  if (fs.existsSync(envPath)) {
    const existing = readEnvFile(envPath);
    if (existing.OCENKA_SEED_PASSWORD && existing.OCENKA_SEED_PASSWORD !== 'replace-with-strong-password') {
      return { created: false, password: existing.OCENKA_SEED_PASSWORD, env: existing };
    }
  }

  const password = crypto.randomBytes(9).toString('base64url');
  const base = fs.existsSync(envExample)
    ? fs.readFileSync(envExample, 'utf8')
    : '# Auto-generated by npm run deploy\n';
  const next = base.includes('OCENKA_SEED_PASSWORD=')
    ? base.replace(/OCENKA_SEED_PASSWORD=.*/m, `OCENKA_SEED_PASSWORD=${password}`)
    : `${base.trim()}\nOCENKA_SEED_PASSWORD=${password}\n`;
  fs.writeFileSync(envPath, next.endsWith('\n') ? next : `${next}\n`);
  return { created: true, password, env: readEnvFile(envPath) };
}

function run(command, args) {
  const result = spawnSync(command, args, {
    cwd: rootDir,
    stdio: 'inherit',
    shell: process.platform === 'win32',
    env: process.env,
  });
  if (result.error) throw result.error;
  if (result.status !== 0) process.exit(result.status || 1);
}

function probeHealth(port) {
  return new Promise((resolve) => {
    const req = http.get({ host: '127.0.0.1', port, path: '/healthz', timeout: 2000 }, (res) => {
      let body = '';
      res.setEncoding('utf8');
      res.on('data', (chunk) => { body += chunk; });
      res.on('end', () => {
        try {
          const json = JSON.parse(body);
          resolve(res.statusCode === 200 && json.status === 'ok');
        } catch {
          resolve(false);
        }
      });
    });
    req.on('error', () => resolve(false));
    req.on('timeout', () => { req.destroy(); resolve(false); });
  });
}

async function waitHealthy(timeoutMs = 120000) {
  const started = Date.now();
  process.stdout.write('Ожидание готовности');
  while (Date.now() - started < timeoutMs) {
    if (await probeHealth(80) || await probeHealth(4173)) {
      process.stdout.write('\n');
      return true;
    }
    process.stdout.write('.');
    await new Promise((resolve) => setTimeout(resolve, 1500));
  }
  process.stdout.write('\n');
  return false;
}

async function main() {
  const docker = spawnSync('docker', ['compose', 'version'], {
    cwd: rootDir,
    encoding: 'utf8',
    shell: process.platform === 'win32',
  });
  if (docker.status !== 0) {
    console.error('Docker Compose не найден. Установите Docker Desktop и повторите: npm run deploy');
    process.exit(1);
  }

  const { created, password, env } = ensureEnv();
  console.log(created ? `Создан .env, пароль входа: ${password}` : 'Используется существующий .env');
  console.log('Сборка и запуск контейнеров (приложение + Caddy)...');
  run('docker', ['compose', 'up', '-d', '--build']);

  const ok = await waitHealthy();
  if (!ok) {
    console.error('Сервис не ответил на /healthz вовремя. Смотрите: docker compose logs -f');
    process.exit(1);
  }

  const domain = String(env.OCENKA_DOMAIN || '').trim();
  const publicUrl = domain ? `https://${domain}/` : 'http://localhost/';

  console.log('');
  console.log('Готово.');
  console.log(`  URL:   ${publicUrl}`);
  if (!domain) console.log('  (или http://IP_СЕРВЕРА/ — порт 80, без :4173)');
  console.log('  Логин: ocenka');
  console.log(`  Пароль: ${password}`);
  console.log('');
  console.log('Домен:  пропишите A-запись на IP сервера и задайте OCENKA_DOMAIN в .env');
  console.log('Логи:   docker compose logs -f');
  console.log('Стоп:   docker compose down');
}

main().catch((error) => {
  console.error(error.message || error);
  process.exit(1);
});
